Typo fix
Didn't change the compiler handle to the correct setting when I moved the check to that part of the build.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -174,11 +174,11 @@ jobs:
              echo "Using RANLIB: $RANLIB"
 
              # Check if the correct compiler is set. 
-             if ! $ICPX --version; then
-                 echo "Error: icpx compiler not found!"
+             if ! $CXX --version; then
+                 echo "Error: $CXX compiler not found!"
                  exit 1
              fi
-             $ICPX --version
+             $CXX --version
              
              # Configure Meson with the corrected syntax for cpp_args
              $MESON_CMD -Dsycl=l0 \
